# Generated by Django 4.2.9 on 2026-06-04 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0002_add_completion_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_type',
            field=models.CharField(max_length=100),
        ),
    ]
